defaults:
  - animation: 3D
  - shunt

scenes: deep space habitation ring made of glass | galactic nebula | wow! space is
  full of fractal creatures darting around everywhere like fireflies
scene_prefix: 'astrophotography #pixelart | image credit nasa | space full of cybernetic
  neon:3_galactic nebula | isometric pixelart by Sachin Teng | '
scene_suffix: '| satellite image:-1:-.95 | text:-1:-.95 | anime:-1:-.95 | watermark:-1:-.95
  | backyard telescope:-1:-.95 | map:-1:-.95'
interpolation_steps: 0
steps_per_scene: 100
direct_image_prompts: https://i.imgur.com/frXoHJ6.jpg
init_image: ''
direct_init_weight: ''
semantic_init_weight: ''
image_model: Limited Palette
width: 180
height: 112
pixel_size: 4
smoothing_weight: 0.02
vqgan_model: sflckr
random_initial_palette: false
palette_size: 6
palettes: 9
gamma: 1
hdr_weight: 0.01
palette_normalization_weight: 0.2
show_palette: false
target_palette: ''
lock_palette: false
sampling_mode: bicubic
infill_mode: wrap
pre_animation_steps: 100
steps_per_frame: 50
frames_per_second: 12
direct_stabilization_weight: ''
semantic_stabilization_weight: ''
depth_stabilization_weight: ''
edge_stabilization_weight: ''
flow_stabilization_weight: ''
video_path: ''
frame_stride: 1
reencode_each_frame: true
flow_long_term_samples: 1
translate_x: -1700*sin(radians(1.5))
translate_y: '0'
rotate_2d: '5'
zoom_x_2d: '0'
zoom_y_2d: '0'
lock_camera: true
field_of_view: 60
near_plane: 1
far_plane: 10000
file_namespace: default
allow_overwrite: false
display_every: 50
clear_every: 0
display_scale: 1
save_every: 50
backups: 5
show_graphs: false
approximate_vram_usage: false
ViTB32: true
ViTB16: false
RN50: false
RN50x4: false
learning_rate: null
reset_lr_each_frame: true
seed: -4854551145582748953
cutouts: 40
cut_pow: 2
cutout_border: 0.25
border_mode: clamp
